-- Task #178: Recurring weekly club slots.
-- Adds a nullable text column linking slots that were created together
-- as part of a "repeat weekly" publish action. The id is generated by
-- the API (uuid) so cancel-this-and-future can target the series.
--
-- Apply manually with:
--   psql "$DATABASE_URL" -f lib/db/migrations/0004_club_slots_recurring.sql
--
-- Safe to re-run.

BEGIN;

ALTER TABLE club_slots
  ADD COLUMN IF NOT EXISTS recurring_series_id text;

CREATE INDEX IF NOT EXISTS club_slots_recurring_series_idx
  ON club_slots (recurring_series_id)
  WHERE recurring_series_id IS NOT NULL;

COMMIT;
